#pragma once

#include "DrillLib.h"

#define SPV_NULL_ID 0u

namespace SPIRV {

enum SourceLanguage {
	SOURCE_LANGUAGE_UNKNOWN = 0,
	SOURCE_LANGUAGE_ESSL = 1,
	SOURCE_LANGUAGE_GLSL = 2,
	SOURCE_LANGUAGE_OPENCL_C = 3,
	SOURCE_LANGUAGE_OPENCL_CPP = 4,
	SOURCE_LANGUAGE_HLSL = 5,
	SOURCE_LANGUAGE_CPP_FOR_OPENCL = 6,
	SOURCE_LANGUAGE_SYCL = 7
};

enum ExecutionModel {
	EXECUTION_MODEL_VERTEX = 0,
	EXECUTION_MODEL_TESSELLATION_CONTROL = 1,
	EXECUTION_MODEL_TESSELLATION_EVALUATION = 2,
	EXECUTION_MODEL_GEOMETRY = 3,
	EXECUTION_MODEL_FRAGMENT = 4,
	EXECUTION_MODEL_GL_COMPUTE = 5,
	EXECUTION_MODEL_KERNEL = 6,
	EXECUTION_MODEL_TASK_NV = 5267,
	EXECUTION_MODEL_MESH_NV = 5268,
	EXECUTION_MODEL_RAY_GENERATION_NV = 5313,
	EXECUTION_MODEL_KHR = EXECUTION_MODEL_RAY_GENERATION_NV,
	EXECUTION_MODEL_INTERSECTION_NV = 5314,
	EXECUTION_MODEL_INTERSECTION_KHR = EXECUTION_MODEL_INTERSECTION_NV,
	EXECUTION_MODEL_ANY_HIT_NV = 5315,
	EXECUTION_MODEL_ANY_HIT_KHR = EXECUTION_MODEL_ANY_HIT_NV,
	EXECUTION_MODEL_CLOSEST_HIT_NV = 5316,
	EXECUTION_MODEL_CLOSEST_HIT_KHR = EXECUTION_MODEL_CLOSEST_HIT_NV,
	EXECUTION_MODEL_MISS_NV = 5317,
	EXECUTION_MODEL_MISS_KHR = EXECUTION_MODEL_MISS_NV,
	EXECUTION_MODEL_CALLABLE_NV = 5318,
	EXECUTION_MODEL_CALLABLE_KHR = EXECUTION_MODEL_CALLABLE_NV,
	EXECUTION_MODEL_Invalid = 0xFFFF
};

enum AddressingModel {
	ADDRESSING_MODEL_LOGICAL = 0,
	ADDRESSING_MODEL_PHYSICAL_32 = 1,
	ADDRESSING_MODEL_PHYSICAL_64 = 2,
	ADDRESSING_MODEL_PHYSICAL_STORAGE_BUFFER_64 = 5348,
	ADDRESSING_MODEL_PHYSICAL_STORAGE_BUFFER_64_EXT = ADDRESSING_MODEL_PHYSICAL_STORAGE_BUFFER_64
};

enum MemoryModel {
	MEMORY_MODEL_SIMPLE = 0,
	MEMORY_MODEL_GLSL450 = 1,
	MEMORY_MODEL_OPENCL = 2,
	MEMORY_MODEL_VULKAN = 3,
	MEMORY_MODEL_VULKAN_KHR = MEMORY_MODEL_VULKAN
};

enum ExecutionMode {
	EXECUTION_MODE_INVOCATIONS = 0,
	EXECUTION_MODE_SPACING_EQUAL = 1,
	EXECUTION_MODE_SPACING_FRACTIONAL_EVEN = 2,
	EXECUTION_MODE_SPACING_FRACTIONAL_ODD = 3,
	EXECUTION_MODE_VERTEX_ORDER_CW = 4,
	EXECUTION_MODE_VERTEX_ORDER_CCW = 5,
	EXECUTION_MODE_PIXEL_CENTER_INTEGER = 6,
	EXECUTION_MODE_ORIGIN_UPPER_LEFT = 7,
	EXECUTION_MODE_ORIGIN_LOWER_LEFT = 8,
	EXECUTION_MODE_EARLY_FRAGMENT_TESTS = 9,
	EXECUTION_MODE_POINT_MODE = 10,
	EXECUTION_MODE_XFB = 11,
	EXECUTION_MODE_DEPTH_REPLACING = 12,
	EXECUTION_MODE_DEPTH_GREATER = 14,
	EXECUTION_MODE_DEPTH_LESS = 15,
	EXECUTION_MODE_DEPTH_UNCHANGED = 16,
	EXECUTION_MODE_LOCAL_SIZE = 17,
	EXECUTION_MODE_LOCAL_SIZE_HINT = 18,
	EXECUTION_MODE_INPUT_POINTS = 19,
	EXECUTION_MODE_INPUT_LINES = 20,
	EXECUTION_MODE_INPUT_LINES_ADJACENCY = 21,
	EXECUTION_MODE_TRIANGLES = 22,
	EXECUTION_MODE_INPUT_TRIANGLES_ADJACENCY = 23,
	EXECUTION_MODE_QUADS = 24,
	EXECUTION_MODE_ISOLINES = 25,
	EXECUTION_MODE_OUTPUT_VERTICES = 26,
	EXECUTION_MODE_OUTPUT_POINTS = 27,
	EXECUTION_MODE_OUTPUT_LINE_STRIP = 28,
	EXECUTION_MODE_OUTPUT_TRIANGLE_STRIP = 29,
	EXECUTION_MODE_VEC_TYPE_HINT = 30,
	EXECUTION_MODE_CONTRACTION_OFF = 31,
	EXECUTION_MODE_INITIALIZER = 33,
	EXECUTION_MODE_FINALIZER = 34,
	EXECUTION_MODE_SUBGROUP_SIZE = 35,
	EXECUTION_MODE_SUBGROUPS_PER_WORKGROUP = 36,
	EXECUTION_MODE_SUBGROUPS_PER_WORKGROUP_ID = 37,
	EXECUTION_MODE_LOCAL_SIZE_ID = 38,
	EXECUTION_MODE_LOCAL_SIZE_HINT_ID = 39,
	EXECUTION_MODE_SUBGROUP_UNIFORM_CONTROL_FLOW_KHR = 4421,
	EXECUTION_MODE_POST_DEPTH_COVERAGE = 4446,
	EXECUTION_MODE_DENORM_PRESERVE = 4459,
	EXECUTION_MODE_DENORM_FLUSH_TO_ZERO = 4460,
	EXECUTION_MODE_SIGNED_ZERO_INF_NAN_PERSERVE = 4461,
	EXECUTION_MODE_ROUNDING_MODE_RTE = 4462,
	EXECUTION_MODE_ROUNDING_MODE_RTZ = 4463,
	EXECUTION_MODE_EARLY_AND_LATE_FRAGMENT_TESTS_AMD = 5017,
	EXECUTION_MODE_STENCIL_REF_REPLACING_EXT = 5027,
	EXECUTION_MODE_STENCIL_REF_UNCHANGED_FRONT_AMD = 5079,
	EXECUTION_MODE_STENCIL_REF_GREATER_FRONT_AMD = 5080,
	EXECUTION_MODE_STENCIL_REF_LESS_FRONT_AMD = 5081,
	EXECUTION_MODE_STENCIL_REF_UNCHANGED_BACK_AMD = 5082,
	EXECUTION_MODE_STENCIL_REF_GREATER_BACK_AMD = 5083,
	EXECUTION_MODE_STENCIL_REF_LESS_BACK_AMD = 5084,
	EXECUTION_MODE_OUTPUT_LINES_NV = 5269,
	EXECUTION_MODE_OUTPUT_PRIMITIVES_NV = 5270,
	EXECUTION_MODE_DERIVATIVE_GROUP_QUADS_NV = 5289,
	EXECUTION_MODE_DERIVATIVE_GROUP_LINEAR_NV = 5290,
	EXECUTION_MODE_OUTPUT_TRIANGLES_NV = 5298,
	EXECUTION_MODE_PIXEL_INTERLOCK_ORDERED_EXT = 5366,
	EXECUTION_MODE_PIXEL_INTERLOCK_UNORDERED_EXT = 5367,
	EXECUTION_MODE_SAMPLER_INTERLOCK_ORDERED_EXT = 5368,
	EXECUTION_MODE_SAMPLER_INTERLOCK_UNORDERED_EXT = 5369,
	EXECUTION_MODE_SHADING_RATE_INTERLOCK_ORDERED_EXT = 5370,
	EXECUTION_MODE_SHADING_RATE_INTERLOCK_UNORDERED_EXT = 5371,
	EXECUTION_MODE_SHARED_LOCAL_MEMORY_SIZE_INTEL = 5618,
	EXECUTION_MODE_ROUNDING_MODE_RTP_INTEL = 5620,
	EXECUTION_MODE_ROUNDING_MODE_RTN_INTEL = 5621,
	EXECUTION_MODE_FLOATING_POINT_MODE_ALT_INTEL = 5622,
	EXECUTION_MODE_FLOATING_POINT_MODE_IEEE_INTEL = 5623,
	EXECUTION_MODE_MAX_WORKGROUP_SIZE_INTEL = 5893,
	EXECUTION_MODE_MAX_WORK_DIM_INTEL = 5894,
	EXECUTION_MODE_NO_GLOBAL_OFFSET_INTEL = 5895,
	EXECUTION_MODE_NUM_SIMD_WORKITEMS_INTEL = 5896,
	EXECUTION_MODE_SCHEDULER_TARGET_FMAX_MHZ_INTEL = 5903,
	EXECUTION_MODE_NAMED_BARRIER_COUNT_INTEL = 6417
};

enum StorageClass {
	STORAGE_CLASS_UNIFORM_CONSTANT = 0,
	STORAGE_CLASS_INPUT = 1,
	STORAGE_CLASS_UNIFORM = 2,
	STORAGE_CLASS_OUTPUT = 3,
	STORAGE_CLASS_WORKGROUP = 4,
	STORAGE_CLASS_CROSS_WORKGROUP = 5,
	STORAGE_CLASS_PRIVATE = 6,
	STORAGE_CLASS_FUNCTION = 7,
	STORAGE_CLASS_GENERIC = 8,
	STORAGE_CLASS_PUSH_CONSTANT = 9,
	STORAGE_CLASS_ATOMIC_COUNTER = 10,
	STORAGE_CLASS_IMAGE = 11,
	STORAGE_CLASS_STORAGE_BUFFER = 12,
	STORAGE_CLASS_CALLABLE_DATA_NV = 5328,
	STORAGE_CLASS_CALLABLE_DATA_KHR = STORAGE_CLASS_CALLABLE_DATA_NV,
	STORAGE_CLASS_INCOMING_CALLABLE_DATA_NV = 5329,
	STORAGE_CLASS_INCOMING_CALLABLE_DATA_KHR = STORAGE_CLASS_INCOMING_CALLABLE_DATA_NV,
	STORAGE_CLASS_RAY_PAYLOAD_NV = 5338,
	STORAGE_CLASS_RAY_PAYLOAD_KHR = STORAGE_CLASS_RAY_PAYLOAD_NV,
	STORAGE_CLASS_HIT_ATTRIBUTE_NV = 5339,
	STORAGE_CLASS_HIT_ATTRIBUTE_KHR = STORAGE_CLASS_HIT_ATTRIBUTE_NV,
	STORAGE_CLASS_INCOMING_RAY_PAYLOAD_NV = 5342,
	STORAGE_CLASS_INCOMING_RAY_PAYLOAD_KHR = STORAGE_CLASS_INCOMING_RAY_PAYLOAD_NV,
	STORAGE_CLASS_SHADER_RECORD_BUFFER_NV = 5343,
	STORAGE_CLASS_SHADER_RECORD_BUFFER_KHR = STORAGE_CLASS_SHADER_RECORD_BUFFER_NV,
	STORAGE_CLASS_PHYSICAL_STORAGE_BUFFER = 5349,
	STORAGE_CLASS_PHYSICAL_STORAGE_BUFFER_EXT = STORAGE_CLASS_PHYSICAL_STORAGE_BUFFER,
	STORAGE_CLASS_CODE_SECTION_INTEL = 5605,
	STORAGE_CLASS_DEVICE_ONLY_INTEL = 5936,
	STORAGE_CLASS_HOST_ONLY_INTEL = 5937,

	STORAGE_CLASS_Invalid = 0xFFFF
};

enum AccessQualifier {
	ACCESS_QUALIFIER_READ_ONLY = 0,
	ACCESS_QUALIFIER_WRITE_ONLY = 1,
	ACCESS_QUALIFIER_READ_WRITE = 2,

	ACCESS_QUALIFIER_Invalid = 0xFFFF
};

enum Capability {
	CAPABILITY_MATRIX = 0,
	CAPABILITY_SHADER = 1,
	CAPABILITY_GEOMETRY = 2,
	CAPABILITY_TESSELLATION = 3,
	CAPABILITY_ADDRESSES = 4,
	CAPABILITY_LINKAGE = 5,
	CAPABILITY_KERNEL = 6,
	CAPABILITY_VECTOR16 = 7,
	CAPABILITY_FLOAT16_BUFFER = 8,
	CAPABILITY_FLOAT16 = 9,
	CAPABILITY_FLOAT64 = 10,
	CAPABILITY_INT64 = 11,
	CAPABILITY_INT64_ATOMICS = 12,
	CAPABILITY_IMAGE_BASIC = 13,
	CAPABILITY_IMAGE_READ_WRITE = 14,
	CAPABILITY_IMAGE_MIPMAP = 15,
	CAPABILITY_PIPES = 17,
	CAPABILITY_GROUPS = 18,
	CAPABILITY_DEVICE_ENQUEUE = 19,
	CAPABILITY_LITERAL_SAMPLER = 20,
	CAPABILITY_ATOMIC_STORAGE = 21,
	CAPABILITY_INT16 = 22,
	CAPABILITY_TESSELLATION_POINT_SIZE = 23,
	CAPABILITY_GEOMETRY_POINT_SIZE = 24,
	CAPABILITY_IMAGE_GATHER_EXTENDED = 25,
	CAPABILITY_STORAGE_IMAGE_MULTISAMPLE = 27,
	CAPABILITY_UNIFORM_BUFFER_ARRAY_DYNAMIC_INDEXING = 28,
	CAPABILITY_SAMPLED_IMAGE_ARRAY_DYNAMIC_INDEXING = 29,
	CAPABILITY_STORAGE_BUFFER_ARRAY_DYNAMIC_INDEXING = 30,
	CAPABILITY_STORAGE_IMAGE_ARRAY_DYNAMIC_INDEXING = 31,
	CAPABILITY_CLIP_DISTANCE = 32,
	CAPABILITY_CULL_DISTANCE = 33,
	CAPABILITY_IMAGE_CUBE_ARRAY = 34,
	CAPABILITY_SAMPLER_RATE_SHADING = 35,
	CAPABILITY_IMAGE_RECT = 36,
	CAPABILITY_SAMPLED_RECT = 37,
	CAPABILITY_GENERIC_POINTER = 38,
	CAPABILITY_INT8 = 39,
	CAPABILITY_INPUT_ATTACHMENT = 40,
	CAPABILITY_SPARCE_RESIDENCY = 41,
	CAPABILITY_MIN_LOD = 42,
	CAPABILITY_SAMPLED_1D = 43,
	CAPABILITY_IMAGE_1D = 44,
	CAPABILITY_SAMPLED_CUBE_ARRAY = 45,
	CAPABILITY_SAMPLED_BUFFER = 46,
	CAPABILITY_IMAGE_BUFFER = 47,
	CAPABILITY_IMAGE_MS_ARRAY = 48,
	CAPABILITY_STORAGE_IMAGE_EXTENDED_FORMATS = 49,
	CAPABILITY_IMAGE_QUERY = 50,
	CAPABILITY_DERIVATIVE_CONTROL = 51,
	CAPABILITY_INTERPOLATION_FUNCTION = 52,
	CAPABILITY_TRANSFORM_FEEDBACK = 53,
	CAPABILITY_GEOMETRY_STREAMS = 54,
	CAPABILITY_STORAGE_IMAGE_READ_WITHOUT_FORMAT = 55,
	CAPABILITY_STORAGE_IMAGE_WRITE_WITHOUT_FORMAT = 56,
	CAPABILITY_MULTI_VIEWPORT = 57,
	CAPABILITY_SUBGROUP_DISPATCH = 58,
	CAPABILITY_NAMED_BARRIER = 59,
	CAPABILITY_PIPE_STORAGE = 60,
	CAPABILITY_GROUP_NON_UNIFORM = 61,
	CAPABILITY_GROUP_NON_UNIFORM_VOTE = 62,
	CAPABILITY_GROUP_NON_UNIFORM_ARITHMETIC = 63,
	CAPABILITY_GROUP_NON_UNIFORM_BALLOT = 64,
	CAPABILITY_GROUP_NON_UNIFORM_SHUFFLE = 65,
	CAPABILITY_GROUP_NON_UNIFORM_SHUFFLE_RELATIVE = 66,
	CAPABILITY_GROUP_NON_UNIFORM_CLUSTERED = 67,
	CAPABILITY_GROUP_NON_UNIFORM_QUAD = 68,
	CAPABILITY_SHADER_LAYER = 69,
	CAPABILITY_SHADER_VIEWPORT_INDEX = 70,
	CAPABILITY_UNIFORM_DECORATION = 71,
	CAPABILITY_FRAGMENT_SHADING_RATE_KHR = 4422,
	CAPABILITY_SUBGROUP_BALLOT_KHR = 4423,
	CAPABILITY_DRAW_PARAMETERS = 4427,
	// Got tired of typing all these out, so I just typed the ones I thought I might use with //... for the missing ones
	// ...
	CAPABILITY_SUBGROUP_VOTE_KHR = 4431,
	// ...
	CAPABILITY_MULTIVIEW = 4439,
	// ...
	CAPABILITY_FRAGMENT_BARYCENTRIC_NV = 5284,
	CAPABILITY_FRAGMENT_BARYCENTRIC_KHR = CAPABILITY_FRAGMENT_BARYCENTRIC_NV,
	CAPABILITY_COMPUTE_DERIVATIVE_GROUP_QUADS_NV = 5288,
	CAPABILITy_FRAGMENT_DENSITY_EXT = 5291,
	CAPABILITY_SHADING_RATE_NV = CAPABILITy_FRAGMENT_DENSITY_EXT,
	CAPABILITY_GROUP_NON_UNIFORM_PARTITIONED_NV = 5297,
	CAPABILITY_SHADER_NON_UNIFORM = 5301,
	CAPABILITY_SHADER_NON_UNIFORM_EXT = CAPABILITY_SHADER_NON_UNIFORM,
	CAPABILITY_RUNTIME_DESCRIPTOR_ARRAY = 5302,
	CAPABILITY_RUNTIME_DESCRIPTOR_ARRAY_EXT = CAPABILITY_RUNTIME_DESCRIPTOR_ARRAY,
	CAPABILITY_INPUT_ATTACHMENT_ARRAY_DYNAMIC_INDEXING = 5303,
	CAPABILITY_INPUT_ATTACHMENT_ARRAY_DYNAMIC_INDEXING_EXT = CAPABILITY_INPUT_ATTACHMENT_ARRAY_DYNAMIC_INDEXING,
	CAPABILITY_UNIFORM_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING = 5304,
	CAPABILITY_UNIFORM_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING_EXT = CAPABILITY_UNIFORM_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING,
	CAPABILITY_STORAGE_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING = 5305,
	CAPABILITY_STORAGE_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING_EXT = CAPABILITY_STORAGE_TEXEL_BUFFER_ARRAY_DYNAMIC_INDEXING,
	CAPABILITY_UNIFORM_BUFFER_ARRAY_NON_UNIFORM_INDEXING = 5306,
	CAPABILITY_UNIFORM_BUFFER_ARRAY_NON_UNIFORM_INDEXING_EXT = CAPABILITY_UNIFORM_BUFFER_ARRAY_NON_UNIFORM_INDEXING,
	CAPABILITY_SAMPLED_IMAGE_ARRAY_NON_UNIFORM_INDEXING = 5307,
	CAPABILITY_SAMPLED_IMAGE_ARRAY_NON_UNIFORM_INDEXING_EXT = CAPABILITY_SAMPLED_IMAGE_ARRAY_NON_UNIFORM_INDEXING,
	CAPABILITY_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING = 5308,
	CAPABILITY_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING_EXT = CAPABILITY_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING,
	CAPABILITY_STORAGE_IMAGE_ARRAY_NON_UNIFORM_INDEXING = 5309,
	CAPABILITY_STORAGE_IMAGE_ARRAY_NON_UNIFORM_INDEXING_EXT = CAPABILITY_STORAGE_IMAGE_ARRAY_NON_UNIFORM_INDEXING,
	CAPABILITY_INPUT_ATTACHMENT_ARRAY_NON_UNIFORM_INDEXING = 5310,
	CAPABILITY_INPUT_ATTACHMENT_ARRAY_NON_UNIFORM_INDEXING_EXT = CAPABILITY_INPUT_ATTACHMENT_ARRAY_NON_UNIFORM_INDEXING,
	CAPABILITY_UNIFORM_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING = 5311,
	CAPABILITY_UNIFORM_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING_EXT = CAPABILITY_UNIFORM_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING,
	CAPABILITY_STORAGE_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING = 5312,
	CAPABILITY_STORAGE_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING_EXT = CAPABILITY_STORAGE_TEXEL_BUFFER_ARRAY_NON_UNIFORM_INDEXING,
	CAPABILITY_RAY_TRACING_NV = 5340,
	CAPABILITY_RAY_TRACING_MOTION_BLUR_NV = 5341,
	CAPABILITY_VULKAN_MEMORY_MODEL = 5345,
	CAPABILITY_VULKAN_MEMORY_MODEL_KHR = CAPABILITY_VULKAN_MEMORY_MODEL,
	CAPABILITY_VULKAN_MEMORY_MODEL_DEVICE_SCOPE = 5346,
	CAPABILITY_VULKAN_MEMORY_MODEL_DEVICE_SCOPE_KHR = CAPABILITY_VULKAN_MEMORY_MODEL_DEVICE_SCOPE,
	CAPABILITY_PHYSICAL_STORAGE_BUFFER_ADDRESSES = 5347,
	CAPABILITY_PHYSICAL_STORAGE_BUFFER_ADDRESSES_EXT = CAPABILITY_PHYSICAL_STORAGE_BUFFER_ADDRESSES,
	// ...
	CAPABILITY_DEMOTE_TO_HELPER_INVOCATION = 5379,
	CAPABILITY_DEMOTE_TO_HELPER_INVOCATION_EXT = CAPABILITY_DEMOTE_TO_HELPER_INVOCATION,
	// ...
	CAPABILITY_DOT_PRODUCT_INPUT_ALL = 6016,
	CAPABILITY_DOT_PRODUCT_INPUT_ALL_KHR = CAPABILITY_DOT_PRODUCT_INPUT_ALL,
	// ...
	CAPABILITY_DOT_PRODUCT = 6019,
	CAPABILITY_DOT_PRODUCT_KHR = CAPABILITY_DOT_PRODUCT,
	CAPABILITY_RAY_CULL_MASK_KHR = 6020,
	CAPABILITY_BIT_INSTRUCTIONS = 6025,
	CAPABILITY_GROUP_NON_UNIFORM_ROTATE_KHR = 6026,
	// ...
	CAPABILITY_GROUP_UNIFORM_ARITHEMTIC_KHR = 6400
};

enum FunctionParameterAttribute {
	// Zero extend
	FUNCTION_PARAMETER_ATTRIBUTE_ZEXT = 0,
	// Sign extend
	FUNCTION_PARAMETER_ATTRIBUTE_SEXT = 1,
	// Pass by value
	FUNCTION_PARAMETER_ATTRIBUTE_BY_VAL = 2,
	// This parameter is the address of the return value for this function
	FUNCTION_PARAMETER_ATTRIBUTE_SRET = 3,
	// Pointer parameter does not alias through pointers not derived from it
	FUNCTION_PARAMETER_ATTRIBUTE_NO_ALIAS = 4,
	// Parameter is not copied into a location accessible after returning
	FUNCTION_PARAMETER_ATTRIBUTE_NO_CAPTURE = 5,
	// Memory pointed to by the pointer parameter is not written to
	FUNCTION_PARAMETER_ATTRIBUTE_NO_WRITE = 6,
	// Pointer parameter is not dereferenced, either to read or write the memory pointed to
	FUNCTION_PARAMETER_ATTRIBUTE_NO_READ_WRITE = 7
};
typedef Flags32 FunctionParameterAttributes;

enum Decoration {
	DECORATION_RELAXED_PRECISION = 0,
	DECORATION_SPEC_ID = 1,
	DECORATION_BLOCK = 2,
	// Deprecated
	DECORATION_BUFFER_BLOCK = 3,
	DECORATION_ROW_MAJOR = 4,
	DECORATION_COL_MAJOR = 5,
	DECORATION_ARRAY_STRIDE = 6,
	DECORATION_MATRIX_STRIDE = 7,
	DECORATION_GLSL_SHARED = 8,
	DECORATION_GLSL_PACKED = 9,
	DECORATION_C_PACKED = 10,
	DECORATION_BUILTIN = 11,
	DECORATION_NOPERSPECTIVE = 13,
	DECORATION_FLAT = 14,
	DECORATION_PATCH = 15,
	DECORATION_CENTROID = 16,
	DECORATION_SAMPLE = 17,
	DECORATION_INVARIANT = 18,
	DECORATION_RESTRICT = 19,
	DECORATION_ALIASED = 20,
	//Not allowed in vulkan as a decoration
	DECORATION_VOLATILE = 21,
	DECORATION_CONSTANT = 22,
	//Also not allowed in vulkan as a decoration
	DECORATION_COHERENT = 23,
	DECORATION_NON_WRITABLE = 24,
	DECORATION_NON_READABLE = 25,
	DECORATION_UNIFORM = 26,
	DECORATION_UNIFORM_ID = 27,
	DECORATION_SATURATED_CONVERSION = 28,
	DECORATION_STREAM = 29,
	DECORATION_LOCATION = 30,
	DECORATION_COMPONENT = 31,
	DECORATION_INDEX = 32,
	DECORATION_BINDING = 33,
	DECORATION_DESCRIPTOR_SET = 34,
	DECORATION_OFFSET = 35,
	DECORATION_XFB_BUFFER = 36,
	DECORATION_XFB_STRIDE = 37,
	DECORATION_FUNC_PARAM_ATTR = 38,
	DECORATION_FP_ROUNDING_MODE = 39,
	DECORATION_FP_FAST_MATH_MODE = 40,
	DECORATION_LINKAGE_ATTRIBUTES = 41,
	DECORATION_NO_CONTRACTION = 42,
	DECORATION_INPUT_ATTACHMENT_INDEX = 43,
	DECORATION_ALIGNMENT = 44,
	DECORATION_MAX_BYTE_OFFSET = 45,
	DECORATION_ALIGNMENT_ID = 46,
	DECORATION_MAX_BYTE_OFFSET_ID = 47,
	DECORATION_NO_SIGNED_WRAP = 4469,
	DECORATION_NO_UNSIGNED_WRAP = 4470,
	DECORATION_EXPLICIT_INTERP_AMD = 4999,
	DECORATION_OVERRIDE_COVERAGE_NV = 5248,
	DECORATION_PASSTHROUGH_NV = 5250,
	DECORATION_VIEWPORT_RELATIVE_NV = 5252,
	DECORATION_SECONDARY_VIEWPORT_RELATIVE_NV = 5256,
	DECORATION_PER_PRIMITIVE_NV = 5271,
	DECORATION_PER_VIEW_NV = 5272,
	DECORATION_PER_TASK_NV = 5273,
	DECORATION_PER_VERTEX_KHR = 5285,
	DECORATION_PER_VERTEX_NV = DECORATION_PER_VERTEX_KHR,
	DECORATION_NON_UNIFORM = 5300,
	DECORATION_NON_UNIFORM_EXT = DECORATION_NON_UNIFORM,
	DECORATION_RESTRICT_POINTER = 5355,
	DECORATION_RESTRICT_POINTER_EXT = DECORATION_RESTRICT_POINTER,
	DECORATION_ALIASED_POINTER = 5356,
	DECORATION_ALIASED_POINTER_EXT = DECORATION_ALIASED_POINTER,
	DECORATION_BINDLESS_SAMPLER_NV = 5398,
	DECORATION_BINDLESS_IMAGE_NV = 5399,
	DECORATION_BOUND_SAMPLER_NV = 5400,
	DECORATION_BOUND_IMAGE_NV = 5401,
	DECORATION_SIMT_CALL_INTEL = 5599,
	DECORATION_REFERENCED_INDIRECTLY_INTEL = 5602,
	DECORATION_CLOBBER_INTEL = 5607,
	DECORATION_SIDE_EFFECTS_INTEL = 5608,
	DECORATION_VECTOR_COMPUTE_VARIABLE_INTEL = 5624,
	DECORATION_FUNC_PARAM_IO_KIND_INTEL = 5625,
	DECORATION_VECTOR_COMPUTE_FUNCTION_INTEL = 5626,
	DECORATION_STACK_CALL_INTEL = 5627,
	DECORATION_GLOBAL_VARIABLE_OFFSET_INTEL = 5628,
	DECORATION_COUNTER_BUFFER = 5634,
	DECORATION_HLSL_COUNTER_BUFFER_GOOGLE = DECORATION_COUNTER_BUFFER,
	DECORATION_USER_SEMANTIC = 5635,
	DECORATION_HLSL_SEMANTIC_GOOGLE = DECORATION_USER_SEMANTIC,
	DECORATION_USER_TYPE_GOOGLE = 5636,
	DECORATION_FUNCTION_ROUNDING_MODE_INTEL = 5822,
	DECORATION_FUNCTION_DENORM_MODE_INTEL = 5823,
	DECORATION_REGISTER_INTEL = 5825,
	DECORATION_MEMORY_INTEL = 5826,
	DECORATION_NUMBANKS_INTEL = 5827,
	DECORATION_BANKWIDTH_INTEL = 5828,
	DECORATION_MAX_PRIVATE_COPIES_INTEL = 5829,
	DECORATION_SINGLEPUMP_INTEL = 5830,
	DECORATION_DOUBLEPUMP_INTEL = 5831,
	DECORATION_MAX_REPLICATES_INTEL = 5832,
	DECORATION_SIMPLE_DUAL_PORT_INTEL = 5833,
	DECORATION_MERGE_INTEL = 5834,
	DECORATION_BANK_BITS_INTEL = 5835,
	DECORATION_FORCE_POW2_DEPTH_INTEL = 5836,
	DECORATION_BURST_COALESCE_INTEL = 5899,
	DECORATION_CACHE_SIZE_INTEL = 5900,
	DECORATION_DONT_STATICALLY_COALESCE_INTEL = 5901,
	DECORATION_PREFETCH_INTEL = 5902,
	DECORATION_STALL_ENABLE_INTEL = 5905,
	DECORATION_FUSE_LOOPS_IN_FUNCTION_INTEL = 5907,
	DECORATION_ALIAS_SCOPE_INTEL = 5914,
	DECORATION_NO_ALIAS_INTEL = 5915,
	DECORATION_BUFFER_LOCATION_INTEL = 5921,
	DECORATION_IO_PIPE_STORAGE_INTEL = 5944,
	DECORATION_FUNCTION_FLOATING_POINT_MODE_INTEL = 6080,
	DECORATION_SINGLE_ELEMENT_VECTOR_INTEL = 6085,
	DECORATION_VECTOR_COMPUTE_CALLABLE_FUNCTION_INTEL = 6087,
	DECORATION_MEDIA_BLOCK_IO_INTEL = 6140
};

enum BuiltIn : U32 {
	BUILTIN_POSITION = 0,
	BUILTIN_POINT_SIZE = 1,
	BUILTIN_CLIP_DISTANCE = 3,
	BUILTIN_CULL_DISTANCE = 4,
	BUILTIN_VERTEX_ID = 5,
	BUILTIN_INSTANCE_ID = 6,
	BUILTIN_PRIMITIVE_ID = 7,
	BUILTIN_INVOCATION_ID = 8,
	// Layer selection for multi layer framebuffer
	BUILTIN_LAYER = 9,
	// Viewport selection for viewport transform when using multiple viewports
	BUILTIN_VIEWPORT_INDEX = 10,
	BUILTIN_TESS_LEVEL_OUTER = 11,
	BUILTIN_TESS_LEVEL_INNER = 12,
	BUILTIN_TESS_COORD = 13,
	BUILTIN_PATCH_VERTICES = 14,
	BUILTIN_FRAG_COORD = 15,
	BUILTIN_POINT_COORD = 16,
	BUILTIN_FRONT_FACING = 17,
	BUILTIN_SAMPLE_ID = 18,
	BUILTIN_SAMPLE_POSITION = 19,
	BUILTIN_SAMPLE_MASK = 20,
	BUILTIN_FRAG_DEPTH = 22,
	BUILTIN_HELPER_INVOCATION = 23,
	BUILTIN_NUM_WORKGROUPS = 24,
	BUILTIN_WORKGROUP_SIZE = 25,
	BUILTIN_WORKGROUP_ID = 26,
	BUILTIN_LOCAL_INVOCATION_ID = 27,
	BUILTIN_GLOBAL_INVOCATION_ID = 28,
	BUILTIN_LOCAL_INVOCATION_INDEX = 29,
	BUILTIN_WORK_DIM = 30,
	BUILTIN_GLOBAL_SIZE = 31,
	BUILTIN_ENQUEUED_WORKGROUP_SiZE = 32,
	BUILTIN_GLOBAL_OFFSET = 33,
	BUILTIN_GLOBAL_LINEAR_ID = 34,
	BUILTIN_SUBGROUP_SIZE = 36,
	BUILTIN_SUBGROUP_MAX_SIZE = 37,
	BUILTIN_NUM_SUBGROUPS = 38,
	BUILTIN_NUM_ENQUEUED_SUBGROUPS = 39,
	BUILTIN_SUBGROUP_ID = 40,
	BUILTIN_SUBGROUP_LOCAL_INVOCATION_ID = 41,
	BUILTIN_VERTEX_INDEX = 42,
	BUILTIN_INSTANCE_INDEX = 43,
	BUILTIN_SUBGROUP_EQ_MASK = 4416,
	BUILTIN_SUBGROUP_EQ_MASK_KHR = BUILTIN_SUBGROUP_EQ_MASK,
	BUILTIN_SUBGROUP_GE_MASK = 4417,
	BUILTIN_SUBGROUP_GE_MASK_KHR = BUILTIN_SUBGROUP_GE_MASK,
	BUILTIN_SUBGROUP_GT_MASK = 4418,
	BUILTIN_SUBGROUP_GT_MASK_KHR = BUILTIN_SUBGROUP_GT_MASK,
	BUILTIN_SUBGROUP_LE_MASK = 4419,
	BUILTIN_SUBGROUP_LE_MASK_KHR = BUILTIN_SUBGROUP_LE_MASK,
	BUILTIN_SUBGROUP_LT_MASK = 4420,
	BUILTIN_SUBGROUP_LT_MASK_KHR = BUILTIN_SUBGROUP_LT_MASK,
	BUILTIN_BASE_VERTEX = 4424,
	BUILTIN_BASE_INSTANCE = 4425,
	BUILTIN_DRAW_INDEX = 4426,
	BUILTIN_PRIMITIVE_SHADING_RATE_KHR = 4432,
	BUILTIN_DEVICE_INDEX = 4438,
	BUILTIN_VIEW_INDEX = 4440,
	BUILTIN_SHADING_RATE_KHR = 4444,
	BUILTIN_BARY_COORD_NO_PERSP_AMD = 4992,
	BUILTIN_BARY_COORD_NO_PERSP_CENTROID_AMD = 4993,
	BUILTIN_BARY_COORD_NO_PERSP_SAMPLE_AMD = 4994,
	BUILTIN_BARY_COORD_SMOOTH_AMD = 4995,
	BUILTIN_BARY_COORD_SMOOTH_CENTROID_AMD = 4996,
	BUILTIN_BARY_COORD_SMOOTH_SAMPLE_AMD = 4997,
	BUILTIN_BARY_COORD_PULL_MODEL_AMD = 4998,
	BUILTIN_FRAG_STENCIL_REF_EXT = 5014,
	BUILTIN_VIEWPORT_MASK_NV = 5253,
	BUILTIN_SECONDARY_POSITION_NV = 5257,
	BUILTIN_SECONDARY_VIEWPORT_MASK_NV = 5258,
	BUILTIN_POSITION_PER_VIEW_NV = 5261,
	BUILTIN_VIEWPORT_MASK_PER_VIEW_NV = 5262,
	BUILTIN_FULLY_COVERED_EXT = 5264,
	BUILTIN_TASK_COUNT_NV = 5274,
	BUILTIN_PRIMITIVE_COUNT_NV = 5275,
	BUILTIN_PRIMITIVE_INDICES_NV = 5276,
	BUILTIN_CLIP_DISTANCE_PER_VIEW_NV = 5277,
	BUILTIN_CULL_DISTANCE_PER_VIEW_NV = 5278,
	BUILTIN_LAYER_PER_VIEW_NV = 5279,
	BUILTIN_MESH_VIEW_COUNT_NV = 5280,
	BUILTIN_MESH_VIEW_INDICES_NV = 5281,
	BUILTIN_BARY_COORD_KHR = 5286,
	BUILTIN_BARY_COORD_NV = BUILTIN_BARY_COORD_KHR,
	BUILTIN_BARY_COORD_NO_PERSP_KHR = 5287,
	BUILTIN_BARY_COORD_NO_PERSP_NV = BUILTIN_BARY_COORD_NO_PERSP_KHR,
	BUILTIN_FRAG_SIZE_EXT = 5292,
	BUILTIN_FRAGMENT_SIZE_NV = BUILTIN_FRAG_SIZE_EXT,
	BUILTIN_FRAG_INVOCATION_COUNT_EXT = 5293,
	BUILTIN_INVOCATIONS_PER_PIXEL_NV = BUILTIN_FRAG_INVOCATION_COUNT_EXT,
	BUILTIN_LAUNCH_ID_NV = 5319,
	BUILTIN_LAUNCH_ID_KHR = BUILTIN_LAUNCH_ID_NV,
	BUILTIN_LAUNCH_SIZE_NV = 5320,
	BUILTIN_LAUNCH_SIZE_KHR = BUILTIN_LAUNCH_SIZE_NV,
	BUILTIN_WORLD_RAY_ORIGIN_NV = 5321,
	BUILTIN_WORLD_RAY_ORIGIN_KHR = BUILTIN_WORLD_RAY_ORIGIN_NV,
	BUILTIN_WORLD_RAY_DIRECTION_NV = 5322,
	BUILTIN_WORLD_RAY_DIRECTION_KHR = BUILTIN_WORLD_RAY_DIRECTION_NV,
	BUILTIN_OBJECT_RAY_ORIGIN_NV = 5323,
	BUILTIN_OBJECT_RAY_ORIGIN_KHR = BUILTIN_OBJECT_RAY_ORIGIN_NV,
	BUILTIN_OBJECT_RAY_DIRECTION_NV = 5324,
	BUILTIN_OBJECT_RAY_DIRECTION_KHR = BUILTIN_OBJECT_RAY_DIRECTION_NV,
	BUILTIN_RAY_TMIN_NV = 5325,
	BUILTIN_RAY_TMIN_KHR = BUILTIN_RAY_TMIN_NV,
	BUILTIN_RAY_TMAX_NV = 5326,
	BUILTIN_RAY_TMAX_KHR = BUILTIN_RAY_TMAX_NV,
	BUILTIN_INSTANCE_CUSTOM_INDEX_NV = 5327,
	BUILTIN_INSTANCE_CUSTOM_INDEX_KHR = BUILTIN_INSTANCE_CUSTOM_INDEX_NV,
	BUILTIN_OBJECT_TO_WORLD_NV = 5330,
	BUILTIN_OBJECT_TO_WORLD_KHR = BUILTIN_OBJECT_TO_WORLD_NV,
	BUILTIN_WORLD_TO_OBJECT_NV = 5331,
	BUILTIN_WORLD_TO_OBJECT_KHR = BUILTIN_WORLD_TO_OBJECT_NV,
	BUILTIN_HIT_T_NV = 5332,
	BUILTIN_HIT_KIND_NV = 5333,
	BUILTIN_HIT_KIND_KHR = BUILTIN_HIT_KIND_NV,
	BUILTIN_CURRENT_RAY_TIME_NV = 5334,
	BUILTIN_INCOMING_RAY_FLAGS_NV = 5351,
	BUILTIN_INCOMING_RAY_FLAGS_KHR = BUILTIN_INCOMING_RAY_FLAGS_NV,
	BUILTIN_RAY_GEOMETRY_INDEX_KHR = 5352,
	BUILTIN_WARPS_PER_SM_NV = 5374,
	BUILTIN_SM_COUNT_NV = 5375,
	BUILTIN_WARP_ID_NV = 5376,
	BUILDIN_SM_ID_NV = 5377,
	BUILTIN_CULL_MASK_KHR = 6021,

	BUILTIN_Invalid = 0xFFFF
};

enum SelectionControl {
	SELECTION_CONTROL_NONE = 0,
	SELECTION_CONTROL_FLATTEN = 1,
	SELECTION_CONTROL_DONT_FLATTEN = 2,

	SELECTION_CONTROL_Invalid = 0xFFFF
};

enum LoopControlFlag : Flags32 {
	LOOP_CONTROL_NONE = 0x0,
	LOOP_CONTROL_UNROLL = 0x1,
	LOOP_CONTROL_DONT_UNROLL = 0x2,
	LOOP_CONTROL_DEPENDENCY_INFINITE = 0x4,
	LOOP_CONTROL_DEPENDENCY_LENGTH = 0x8,
	LOOP_CONTROL_MIN_ITERATIONS = 0x10,
	LOOP_CONTROL_MAX_ITERATIONS = 0x20,
	LOOP_CONTROL_ITERATION_MULTIPLE = 0x40,
	LOOP_CONTROL_PEEL_COUNT = 0x80,
	LOOP_CONTROL_PARTIAL_COUNT = 0x100,
	LOOP_CONTROL_INITIATION_INTERVAL_INTEL = 0x10000,
	LOOP_CONTROL_MAX_CONCURRENCY_INTEL = 0x20000,
	LOOP_CONTROL_DEPENDENCY_ARRAY_INTEL = 0x40000,
	LOOP_CONTROL_PIPELINE_ENABLE_INTEL = 0x80000,
	LOOP_CONTROL_LOOP_COALESCE_INTEL = 0x100000,
	LOOP_CONTROL_MAX_INTERLEAVING_INTEL = 0x200000,
	LOOP_CONTROL_SPECULATED_ITERATIONS_INTEL = 0x400000,
	LOOP_CONTROL_NO_FUSION_INTEL = 0x800000
};
typedef Flags32 LoopControl;

// I'm ignoring the INTEL ones. They're most likely irrelevant to me.
const U32 NUM_LOOP_CONTROLS = 9;
const U32 NUM_LOOP_CONTROLS_WITH_ARGUMENT = 6;

enum FunctionControlFlag {
	FUNCTION_CONTROL_NONE = 0x0,
	FUNCTION_CONTROL_INLINE = 0x1,
	FUNCTION_CONTROL_DONT_INLINE = 0x2,
	FUNCTION_CONTROL_PURE = 0x4,
	FUNCTION_CONTROL_CONST = 0x8,
	FUNCTION_CONTROL_OPT_NONE_INTEL = 0x10000
};
typedef Flags32 FunctionControl;

enum MemoryOperandFlag {
	MEMORY_OPERAND_NONE = 0x0,
	MEMORY_OPERAND_VOLATILE = 0x1,
	MEMORY_OPERAND_ALIGNED = 0x2,
	MEMORY_OPERAND_NON_TEMPORAL = 0x4,
	MEMORY_OPERAND_MAKE_POINTER_AVAILABLE = 0x8,
	MEMORY_OPERAND_MAKE_POINTER_AVAILABLE_KHR = MEMORY_OPERAND_MAKE_POINTER_AVAILABLE,
	MEMORY_OPERAND_MAKE_POINTER_VISIBLE = 0x10,
	MEMORY_OPERAND_MAKE_POINTER_VISIBLE_KHR = MEMORY_OPERAND_MAKE_POINTER_VISIBLE,
	MEMORY_OPERAND_NON_PRIVATE_POINTER = 0x20,
	MEMORY_OPERAND_NON_PRIVATE_POINTER_KHR = MEMORY_OPERAND_NON_PRIVATE_POINTER,
	MEMORY_OPERAND_ALIAS_SCOPE_INTEL_MASK = 0x10000,
	MEMORY_OPERAND_NO_ALIAS_INTEL_MASK = 0x20000
};
typedef Flags32 MemoryOperands;

enum Dimensionality {
	DIMENSIONALITY_1D = 0,
	DIMENSIONALITY_2D = 1,
	DIMENSIONALITY_3D = 2,
	DIMENSIONALITY_CUBE = 3,
	DIMENSIONALITY_RECT = 4,
	DIMENSIONALITY_BUFFER = 5,
	DIMENSIONALITY_SUBPASS_DATA = 6,
	DIMENSIONALITY_Invalid = 0xFFFF
};

enum ImageFormat {
	IMAGE_FORMAT_UNKNOWN,
	IMAGE_FORMAT_RGBA32F,
	IMAGE_FORMAT_RGBA16F,
	IMAGE_FORMAT_R32F,
	IMAGE_FORMAT_RGBA8,
	IMAGE_FORMAT_RGBA8SNORM,
	IMAGE_FORMAT_RG32F,
	IMAGE_FORMAT_RG16F,
	IMAGE_FORMAT_R11FG11FB10F,
	IMAGE_FORMAT_R16F,
	IMAGE_FORMAT_RGBA16,
	IMAGE_FORMAT_RGB10A2,
	IMAGE_FORMAT_RG16,
	IMAGE_FORMAT_RG8,
	IMAGE_FORMAT_R16,
	IMAGE_FORMAT_R8,
	IMAGE_FORMAT_RGBA16SNORM,
	IMAGE_FORMAT_RG16SNORM,
	IMAGE_FORMAT_RG8SNORM,
	IMAGE_FORMAT_R16SNORM,
	IMAGE_FORMAT_R8SNORM,
	IMAGE_FORMAT_RGBA32I,
	IMAGE_FORMAT_RGBA16I,
	IMAGE_FORMAT_RGBA8I,
	IMAGE_FORMAT_R32I,
	IMAGE_FORMAT_RG32I,
	IMAGE_FORMAT_RG16I,
	IMAGE_FORMAT_RG8I,
	IMAGE_FORMAT_R16I,
	IMAGE_FORMAT_R8I,
	IMAGE_FORMAT_RGBA32UI,
	IMAGE_FORMAT_RGBA16UI,
	IMAGE_FORMAT_RGBA8UI,
	IMAGE_FORMAT_R32UI,
	IMAGE_FORMAT_RGB10A2UI,
	IMAGE_FORMAT_RG32UI,
	IMAGE_FORMAT_RG16UI,
	IMAGE_FORMAT_RG8UI,
	IMAGE_FORMAT_R16UI,
	IMAGE_FORMAT_R8UI,
	IMAGE_FORMAT_R64UI,
	IMAGE_FORMAT_R64I
};

enum ImageOperand {
	IMAGE_OPERAND_NONE = 0x0,
	IMAGE_OPERAND_BIAS = 0x1,
	IMAGE_OPERAND_LOD = 0x2,
	IMAGE_OPERAND_GRAD = 0x4,
	IMAGE_OPERAND_CONST_OFFSET = 0x8,
	IMAGE_OPERAND_OFFSET = 0x10,
	IMAGE_OPERAND_CONST_OFFSETS = 0x20,
	IMAGE_OPERAND_SAMPLE = 0x40,
	IMAGE_OPERAND_MIN_LOD = 0x80,
	IMAGE_OPERAND_MAKE_TEXEL_AVAILABLE = 0x100,
	IMAGE_OPERAND_MAKE_TEXEL_VISIBLE = 0x200,
	IMAGE_OPERAND_NON_PRIVATE_TEXEL = 0x400,
	IMAGE_OPERAND_VOLATILE_TEXEL = 0x800,
	IMAGE_OPERAND_SIGN_EXTEND = 0x1000,
	IMAGE_OPERAND_ZERO_EXTEND = 0x2000,
	IMAGE_OPERAND_NONTEMPORAL = 0x4000,
	IMAGE_OPERAND_OFFSETS = 0x10000,
};
typedef U32 ImageOperands;

// Again ignoring the INTEL ones
const U32 NUM_MEMORY_OPERANDS = 6;
const U32 NUM_MEMORY_OPERANDS_WITH_ARGUMENT = 3;

typedef U32 SpvId;
typedef U32 SpvDword;


#define SPV_BINARY_OP(name, insnId) SpvId name##(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId operand1, SpvId operand2) {\
	const U32 wordCount = 5;\
	output.push_back(wordCount << 16 | insnId, resultType, resultId, operand1, operand2);\
	return resultId;\
}
#define SPV_UNARY_OP(name, insnId) SpvId name##(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId operand1) {\
	const U32 wordCount = 4;\
	SpvDword insn[]{ wordCount << 16 | insnId, resultType, resultId, operand1 };\
	output.push_back_n(insn, wordCount);\
	return resultId;\
}

void op_capability(ArenaArrayList<SpvDword>& output, Capability cap) {
	const U32 opcode = 17, wordCount = 2;
	output.push_back(wordCount << 16 | opcode);
	output.push_back(cap);
}
void op_extension(ArenaArrayList<SpvDword>& output, StrA name) {
	const U32 opcode = 10, wordCount = 1;
	U32 nameLengthInDwords = U32((name.length + 4) / 4);
	output.push_back(wordCount + nameLengthInDwords << 16 | opcode);
	output.resize(output.size + nameLengthInDwords);
	memcpy(output.data + output.size - nameLengthInDwords, name.str, name.length);
}
void op_ext_inst_import(ArenaArrayList<SpvDword>& output, SpvId resultId, StrA name) {
	const U32 opcode = 11, wordCount = 2;
	U32 nameLengthInDwords = U32((name.length + 4) / 4);
	output.push_back(wordCount + nameLengthInDwords << 16 | opcode, resultId);
	output.resize(output.size + nameLengthInDwords);
	memcpy(output.data + output.size - nameLengthInDwords, name.str, name.length);
}
SpvId op_ext_inst(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId set, SpvDword instruction, SpvDword* operands, U32 operandsLength) {
	const U32 opcode = 12, wordCount = 5;
	output.push_back(wordCount + operandsLength << 16 | opcode, resultType, resultId, set, instruction);
	output.push_back_n(operands, operandsLength);
	return resultId;
}
void op_memory_model(ArenaArrayList<SpvDword>& output, AddressingModel addressingModel, MemoryModel memoryModel) {
	const U32 opcode = 14, wordCount = 3;
	output.push_back(wordCount << 16 | opcode);
	output.push_back(addressingModel);
	output.push_back(memoryModel);
}
void op_entry_point(ArenaArrayList<SpvDword>& output, ExecutionModel executionModel, SpvId entryPoint, StrA name, SpvId* references, U32 referenceCount) {
	const U32 opcode = 15, wordCount = 3;
	U32 nameLengthInDwords = U32((name.length + 4) / 4);
	output.push_back(wordCount + nameLengthInDwords + referenceCount << 16 | opcode);
	output.push_back(executionModel);
	output.push_back(entryPoint);
	output.resize(output.size + nameLengthInDwords);
	memcpy(output.data + output.size - nameLengthInDwords, name.str, name.length);
	output.push_back_n(references, referenceCount);
}
void op_execution_mode(ArenaArrayList<SpvDword>& output, SpvId entrypoint, ExecutionMode executionMode, SpvDword* literals, U32 literalCount) {
	const U32 opcode = 16, wordCount = 3;
	output.push_back(wordCount + literalCount << 16 | opcode);
	output.push_back(entrypoint);
	output.push_back(executionMode);
	output.push_back_n(literals, literalCount);
}

SpvId op_type_void(ArenaArrayList<SpvDword>& output, SpvId resultId) {
	const U32 opcode = 19, wordCount = 2;
	output.push_back(wordCount << 16 | opcode, resultId);
	return resultId;
}
SpvId op_type_bool(ArenaArrayList<SpvDword>& output, SpvId resultId) {
	const U32 opcode = 20, wordCount = 2;
	output.push_back(wordCount << 16 | opcode, resultId);
	return resultId;
}
//For signedness, 0 is unsigned/no sign and 1 is signed
SpvId op_type_int(ArenaArrayList<SpvDword>& output, SpvId resultId, U32 width, U32 signedness) {
	const U32 opcode = 21, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultId, width, signedness);
	return resultId;
}
SpvId op_type_float(ArenaArrayList<SpvDword>& output, SpvId resultId, U32 width) {
	const U32 opcode = 22, wordCount = 3;
	output.push_back(wordCount << 16 | opcode, resultId, width);
	return resultId;
}
SpvId op_type_vector(ArenaArrayList<SpvDword>& output, SpvId resultId, SpvId componentType, U32 componentCount) {
	const U32 opcode = 23, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultId, componentType, componentCount);
	return resultId;
}
SpvId op_type_matrix(ArenaArrayList<SpvDword>& output, SpvId resultId, SpvId columnType, U32 columnCount) {
	const U32 opcode = 24, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultId, columnType, columnCount);
	return resultId;
}
SpvId op_type_array(ArenaArrayList<SpvDword>& output, SpvId resultId, SpvId elementType, SpvId length) {
	const U32 opcode = 28, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultId, elementType, length);
	return resultId;
}
SpvId op_type_runtime_array(ArenaArrayList<SpvDword>& output, SpvId resultId, SpvId elementType) {
	const U32 opcode = 29, wordCount = 3;
	output.push_back(wordCount << 16 | opcode, resultId, elementType);
	return resultId;
}
SpvId op_type_struct(ArenaArrayList<SpvDword>& output, SpvId resultId, SpvId* members, U32 memberCount) {
	const U32 opcode = 30, wordCount = 2;
	output.push_back(wordCount + memberCount << 16 | opcode, resultId);
	output.push_back_n(members, memberCount);
	return resultId;
}
SpvId op_type_pointer(ArenaArrayList<SpvDword>& output, SpvId resultId, StorageClass storageClass, SpvId type) {
	const U32 opcode = 32, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultId, storageClass, type);
	return resultId;
}
SpvId op_type_image(ArenaArrayList<SpvDword>& output, SpvId resultId, SpvId sampledType, Dimensionality dim, U32 depth, U32 arrayed, U32 multisample, U32 sampled, ImageFormat format, AccessQualifier accessQualifier = ACCESS_QUALIFIER_Invalid) {
	const U32 opcode = 25, wordCount = 9u + (accessQualifier != ACCESS_QUALIFIER_Invalid ? 1u : 0u);
	output.push_back(wordCount << 16 | opcode, resultId, sampledType, dim, depth, arrayed, multisample, sampled, format);
	if (accessQualifier != ACCESS_QUALIFIER_Invalid) {
		output.push_back(accessQualifier);
	}
	return resultId;
}
SpvId op_type_sampler(ArenaArrayList<SpvDword>& output, SpvId resultId) {
	const U32 opcode = 26, wordCount = 2;
	output.push_back(wordCount << 16 | opcode, resultId);
	return resultId;
}
SpvId op_type_sampled_image(ArenaArrayList<SpvDword>& output, SpvId resultId, SpvId imageType) {
	const U32 opcode = 27, wordCount = 3;
	output.push_back(wordCount << 16 | opcode, resultId, imageType);
	return resultId;
}
SpvId op_type_function(ArenaArrayList<SpvDword>& output, SpvId resultId, SpvId returnType, SpvId* params, U32 paramCount) {
	const U32 opcode = 33, wordCount = 3;
	output.push_back(wordCount + paramCount << 16 | opcode, resultId, returnType);
	output.push_back_n(params, paramCount);
	return resultId;
}
SpvId op_constant_true(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId) {
	const U32 opcode = 41, wordCount = 3;
	output.push_back(wordCount << 16 | opcode, resultType, resultId);
	return resultId;
}
SpvId op_constant_false(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId) {
	const U32 opcode = 42, wordCount = 3;
	output.push_back(wordCount << 16 | opcode, resultType, resultId);
	return resultId;
}
SpvId op_constant(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, U32 value) {
	const U32 opcode = 43, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, value);
	return resultId;
}
SpvId op_constant(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, U64 value) {
	const U32 opcode = 43, wordCount = 5;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, U32(value), U32(value >> 32));
	return resultId;
}
SpvId op_constant_composite(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvDword* resultConstituents, U32 constituentCount) {
	const U32 opcode = 44, wordCount = 3;
	output.push_back(wordCount + constituentCount << 16 | opcode, resultType, resultId);
	output.push_back_n(resultConstituents, constituentCount);
	return resultId;
}
SpvId op_constant_null(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId) {
	const U32 opcode = 46, wordCount = 3;
	output.push_back(wordCount << 16 | opcode, resultType, resultId);
	return resultId;
}

SpvId op_variable(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, StorageClass storageClass) {
	const U32 opcode = 59, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, storageClass);
	return resultId;
}
SpvId op_variable(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, StorageClass storageClass, SpvId initializer) {
	const U32 opcode = 59, wordCount = 5;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, storageClass, initializer);
	return resultId;
}
SpvId op_load(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId pointer, SpvDword* memoryOperands, U32 memoryOperandCount) {
	const U32 opcode = 61, wordCount = 4;
	output.push_back(wordCount + memoryOperandCount << 16 | opcode, resultType, resultId, pointer);
	output.push_back_n(memoryOperands, memoryOperandCount);
	return resultId;
}
void op_store(ArenaArrayList<SpvDword>& output, SpvId pointer, SpvId object, SpvDword* memoryOperands, U32 memoryOperandCount) {
	const U32 opcode = 62, wordCount = 3;
	output.push_back(wordCount + memoryOperandCount << 16 | opcode, pointer, object);
	output.push_back_n(memoryOperands, memoryOperandCount);
}

SpvId op_access_chain(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId base, U32* indices, U32 numIndices) {
	const U32 opcode = 65, wordCount = 4;
	output.push_back(wordCount + numIndices << 16 | opcode, resultType, resultId, base);
	output.push_back_n(indices, numIndices);
	return resultId;
}
SpvId op_in_bounds_access_chain(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId base, U32* indices, U32 numIndices) {
	const U32 opcode = 66, wordCount = 4;
	output.push_back(wordCount + numIndices << 16 | opcode, resultType, resultId, base);
	output.push_back_n(indices, numIndices);
	return resultId;
}
SpvId op_ptr_access_chain(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId base, SpvId element, U32* indices, U32 numIndices) {
	const U32 opcode = 67, wordCount = 5;
	output.push_back(wordCount + numIndices << 16 | opcode, resultType, resultId, base, element);
	output.push_back_n(indices, numIndices);
	return resultId;
}

SpvId op_array_length(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId structure, U32 arrayMember) {
	const U32 opcode = 68, wordCount = 5;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, structure, arrayMember);
	return resultId;
}

SpvId op_function(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, U32 functionControl, SpvId functionType) {
	const U32 opcode = 54, wordCount = 5;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, functionControl, functionType);
	return resultId;
}
SpvId op_function_parameter(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId) {
	const U32 opcode = 55, wordCount = 3;
	SpvDword insn[]{ wordCount << 16 | opcode, resultType, resultId };
	output.push_back_n(insn, ARRAY_COUNT(insn));
	return resultId;
}
void op_function_end(ArenaArrayList<SpvDword>& output) {
	const U32 opcode = 56, wordCount = 1;
	output.push_back(wordCount << 16 | opcode);
}
SpvId op_function_call(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId function, SpvId* args, U32 argCount) {
	const U32 opcode = 57, wordCount = 4;
	SpvDword insn[]{ wordCount + argCount << 16 | opcode, resultType, resultId, function };
	output.push_back_n(insn, ARRAY_COUNT(insn));
	output.push_back_n(args, argCount);
	return resultId;
}
void op_return(ArenaArrayList<SpvDword>& output) {
	const U32 opcode = 253, wordCount = 1;
	output.push_back(wordCount << 16 | opcode);
}
void op_return_value(ArenaArrayList<SpvDword>& output, SpvId value) {
	const U32 opcode = 254, wordCount = 2;
	output.push_back(wordCount << 16 | opcode);
	output.push_back(value);
}
void op_unreachable(ArenaArrayList<SpvDword>& output) {
	const U32 opcode = 255, wordCount = 1;
	output.push_back(wordCount << 16 | opcode);
}

SPV_UNARY_OP(op_i_negate, 126)
SPV_UNARY_OP(op_u_negate, 126)
SPV_UNARY_OP(op_s_negate, 126)
SPV_UNARY_OP(op_f_negate, 127)
SPV_BINARY_OP(op_i_add, 128)
SPV_BINARY_OP(op_u_add, 128)
SPV_BINARY_OP(op_s_add, 128)
SPV_BINARY_OP(op_f_add, 129)
SPV_BINARY_OP(op_i_sub, 130)
SPV_BINARY_OP(op_u_sub, 130)
SPV_BINARY_OP(op_s_sub, 130)
SPV_BINARY_OP(op_f_sub, 131)
SPV_BINARY_OP(op_i_mul, 132)
SPV_BINARY_OP(op_u_mul, 132)
SPV_BINARY_OP(op_s_mul, 132)
SPV_BINARY_OP(op_f_mul, 133)
SPV_BINARY_OP(op_u_div, 134)
SPV_BINARY_OP(op_s_div, 135)
SPV_BINARY_OP(op_f_div, 136)
SPV_BINARY_OP(op_u_mod, 137)
SPV_BINARY_OP(op_s_mod, 139)
SPV_BINARY_OP(op_f_mod, 141)
SPV_BINARY_OP(op_u_rem, 137)
SPV_BINARY_OP(op_s_rem, 138)
SPV_BINARY_OP(op_f_rem, 140)
SPV_BINARY_OP(op_dot, 148)
SPV_BINARY_OP(op_shift_right_logical, 194)
SPV_BINARY_OP(op_shift_right_arithmetic, 195)
SPV_BINARY_OP(op_shift_left_logical, 196)
SPV_BINARY_OP(op_bit_or, 197)
SPV_BINARY_OP(op_bit_xor, 198)
SPV_BINARY_OP(op_bit_and, 199)
SPV_BINARY_OP(op_i_add_carry, 149)
SPV_BINARY_OP(op_u_mul_extended, 151)
SPV_UNARY_OP(op_bit_not, 200)
SPV_UNARY_OP(op_logical_not, 168)
SpvId op_bitfield_insert(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId base, SpvId insert, SpvId offset, SpvId count) {
	const U32 opcode = 201, wordCount = 7;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, base, insert, offset, count);
	return resultId;
}
SpvId op_bitfield_s_extract(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId base, SpvId offset, SpvId count) {
	const U32 opcode = 202, wordCount = 6;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, base, offset, count);
	return resultId;
}
SpvId op_bitfield_u_extract(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId base, SpvId offset, SpvId count) {
	const U32 opcode = 203, wordCount = 6;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, base, offset, count);
	return resultId;
}
SPV_UNARY_OP(op_bit_reverse, 204)
SPV_UNARY_OP(op_bit_count, 205)

SPV_BINARY_OP(op_i_equal, 170)
SPV_BINARY_OP(op_u_equal, 170)
SPV_BINARY_OP(op_s_equal, 170)
SPV_BINARY_OP(op_i_not_equal, 171)
SPV_BINARY_OP(op_u_not_equal, 171)
SPV_BINARY_OP(op_s_not_equal, 171)
SPV_BINARY_OP(op_u_greater_than, 172)
SPV_BINARY_OP(op_s_greater_than, 173)
SPV_BINARY_OP(op_u_greater_than_or_equal, 174)
SPV_BINARY_OP(op_s_greater_than_or_equal, 175)
SPV_BINARY_OP(op_u_less_than, 176)
SPV_BINARY_OP(op_s_less_than, 177)
SPV_BINARY_OP(op_u_less_than_or_equal, 178)
SPV_BINARY_OP(op_s_less_than_or_equal, 179)
SPV_BINARY_OP(op_f_equal, 180)
SPV_BINARY_OP(op_f_equal_unordered, 181)
SPV_BINARY_OP(op_f_not_equal, 182)
SPV_BINARY_OP(op_f_not_equal_unordered, 183)
SPV_BINARY_OP(op_f_less_than, 184)
SPV_BINARY_OP(op_f_less_than_unordered, 185)
SPV_BINARY_OP(op_f_greater_than, 186)
SPV_BINARY_OP(op_f_greater_than_unordered, 187)
SPV_BINARY_OP(op_f_less_than_or_equal, 188)
SPV_BINARY_OP(op_f_less_than_or_equal_unordered, 189)
SPV_BINARY_OP(op_f_greater_than_or_equal, 190)
SPV_BINARY_OP(op_f_greater_than_or_equal_unordered, 191)
SPV_UNARY_OP(op_any, 154)
SPV_UNARY_OP(op_all, 155)

SPV_UNARY_OP(op_convert_f_to_u, 109)
SPV_UNARY_OP(op_convert_f_to_s, 110)
SPV_UNARY_OP(op_convert_s_to_f, 111)
SPV_UNARY_OP(op_convert_u_to_f, 112)
SPV_UNARY_OP(op_u_convert, 113)
SPV_UNARY_OP(op_s_convert, 114)
SPV_UNARY_OP(op_f_convert, 115)

SPV_UNARY_OP(op_bitcast, 124);
SpvId op_vector_extract_dynamic(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId vector, SpvId index) {
	const U32 opcode = 77, wordCount = 5;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, vector, index);
	return resultId;
}
SpvId op_vector_insert_dynamic(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId vector, SpvId component, SpvId index) {
	const U32 opcode = 78, wordCount = 6;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, vector, component, index);
	return resultId;
}
SpvId op_vector_shuffle(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId vector1, SpvId vector2, U32* indices, U32 numIndices) {
	const U32 opcode = 79, wordCount = 5;
	output.push_back(wordCount + numIndices << 16 | opcode, resultType, resultId, vector1, vector2);
	output.push_back_n(indices, numIndices);
	return resultId;
}
SpvId op_composite_construct(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId* constituents, U32 numConstituents) {
	const U32 opcode = 80, wordCount = 3;
	output.push_back(wordCount + numConstituents << 16 | opcode, resultType, resultId);
	output.push_back_n(constituents, numConstituents);
	return resultId;
}
SpvId op_composite_extract(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId composite, U32* indices, U32 numIndices) {
	const U32 opcode = 81, wordCount = 4;
	output.push_back(wordCount + numIndices << 16 | opcode, resultType, resultId, composite);
	output.push_back_n(indices, numIndices);
	return resultId;
}
SpvId op_composite_insert(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId object, SpvId composite, U32* indices, U32 numIndices) {
	const U32 opcode = 82, wordCount = 5;
	output.push_back(wordCount + numIndices << 16 | opcode, resultType, resultId, object, composite);
	output.push_back_n(indices, numIndices);
	return resultId;
}
// What is the point of this op? Since SPIR-V is SSA shouldn't this be completely pointless?
SPV_UNARY_OP(op_copy_object, 83);

SpvId op_sampled_image(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId image, SpvId sampler) {
	const U32 opcode = 86, wordCount = 5;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, image, sampler);
	return resultId;
}
// TODO image operands
SpvId op_image_sample_implicit_lod(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId sampledImage, SpvId coordinate) {
	const U32 opcode = 87, wordCount = 5;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, sampledImage, coordinate);
	return resultId;
}
SpvId op_image_sample_explicit_lod(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId sampledImage, SpvId coordinate, ImageOperands lodImageOperand, SpvId lod) {
	const U32 opcode = 88, wordCount = 7;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, sampledImage, coordinate, lodImageOperand, lod);
	return resultId;
}
SpvId op_image_read(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId image, SpvId coordinate) {
	const U32 opcode = 98, wordCount = 5;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, image, coordinate);
	return resultId;
}
void op_image_write(ArenaArrayList<SpvDword>& output, SpvId image, SpvId coordinate, SpvId texel) {
	const U32 opcode = 99, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, image, coordinate, texel);
}

SpvId op_phi(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId* variablesAndParents, U32 parentBlockCount) {
	const U32 opcode = 245, wordCount = 3 + parentBlockCount * 2;
	output.push_back(wordCount << 16 | opcode, resultType, resultId);
	output.push_back_n(variablesAndParents, parentBlockCount * 2);
	return resultId;
}
SpvId patch_phi(ArenaArrayList<SpvDword>& output, U32 offset, SpvId* variablesAndParents, U32 parentBlockCount) {
	memcpy(&output.data[offset + 3], variablesAndParents, parentBlockCount * 2 * sizeof(SpvId));
	SpvId resultId = output.data[offset + 2];
	return resultId;
}
void op_loop_merge(ArenaArrayList<SpvDword>& output, SpvId mergeBlock, SpvId continueTarget, LoopControl loopControl, U32* loopControlParams, U32 loopControlParamCount) {
	const U32 opcode = 246, wordCount = 4 + loopControlParamCount;
	output.push_back(wordCount << 16 | opcode, mergeBlock, continueTarget, loopControl);
	output.push_back_n(loopControlParams, loopControlParamCount);
}
void op_selection_merge(ArenaArrayList<SpvDword>& output, SpvId mergeBlock, SelectionControl selectionControl) {
	const U32 opcode = 247, wordCount = 3;
	output.push_back(wordCount << 16 | opcode, mergeBlock, selectionControl);
}
SpvId op_label(ArenaArrayList<SpvDword>& output, SpvId resultId) {
	const U32 opcode = 248, wordCount = 2;
	output.push_back(wordCount << 16 | opcode, resultId);
	return resultId;
}
void op_branch(ArenaArrayList<SpvDword>& output, SpvId branchTarget) {
	const U32 opcode = 249, wordCount = 2;
	output.push_back(wordCount << 16 | opcode, branchTarget);
}
void op_branch_conditional(ArenaArrayList<SpvDword>& output, SpvId condition, SpvId trueTarget, SpvId falseTarget, U32 trueWeight = 0, U32 falseWeight = 0) {
	const U32 opcode = 250, wordCount = trueWeight > 0 && falseWeight > 0 ? 6u : 4u;
	output.push_back(wordCount << 16 | opcode, condition, trueTarget, falseTarget);
	if (trueWeight > 0 && falseWeight > 0) {
		output.push_back(trueWeight, falseWeight);
	}
}
void op_kill(ArenaArrayList<SpvDword>& output) {
	const U32 opcode = 252, wordCount = 1;
	output.push_back(wordCount << 16 | opcode);
}
void op_terminate_invocation(ArenaArrayList<SpvDword>& output) {
	const U32 opcode = 4416, wordCount = 1;
	output.push_back(wordCount << 16 | opcode);
}
void op_demote_to_helper_invocation(ArenaArrayList<SpvDword>& output) {
	const U32 opcode = 5380, wordCount = 1;
	output.push_back(wordCount << 16 | opcode);
}

void op_decorate(ArenaArrayList<SpvDword>& output, SpvId target, Decoration decoration, U32* literals, U32 literalCount) {
	const U32 opcode = 71, wordCount = 3 + literalCount;
	output.push_back(wordCount << 16 | opcode, target, decoration);
	output.push_back_n(literals, literalCount);
}
void op_member_decorate(ArenaArrayList<SpvDword>& output, SpvId structureType, U32 member, Decoration decoration, U32* literals, U32 literalCount) {
	const U32 opcode = 72, wordCount = 4 + literalCount;
	output.push_back(wordCount << 16 | opcode, structureType, member, decoration);
	output.push_back_n(literals, literalCount);
}

SpvId op_dpdx(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId p) {
	const U32 opcode = 207, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, p);
	return resultId;
}
SpvId op_dpdy(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId p) {
	const U32 opcode = 208, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, p);
	return resultId;
}
SpvId op_fwidth(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId p) {
	const U32 opcode = 209, wordCount = 4;
	output.push_back(wordCount << 16 | opcode, resultType, resultId, p);
	return resultId;
}

SpvId op_unpack_unorm4x8(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId p) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 64, &p, 1);
}
SpvId op_length(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 66, &x, 1);
}
SpvId op_distance(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId p0, SpvId p1) {
	SpvId args[2]{ p0, p1 };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 67, args, 2);
}
SpvId op_cross(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId y) {
	SpvId args[2]{ x, y };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 68, args, 2);
}
SpvId op_normalize(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 69, &x, 1);
}
SpvId op_f_min(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId y) {
	SpvId args[2]{ x, y };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 37, args, 2);
}
SpvId op_u_min(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId y) {
	SpvId args[2]{ x, y };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 38, args, 2);
}
SpvId op_s_min(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId y) {
	SpvId args[2]{ x, y };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 39, args, 2);
}
SpvId op_f_max(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId y) {
	SpvId args[2]{ x, y };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 40, args, 2);
}
SpvId op_u_max(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId y) {
	SpvId args[2]{ x, y };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 41, args, 2);
}
SpvId op_s_max(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId y) {
	SpvId args[2]{ x, y };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 42, args, 2);
}
SpvId op_f_clamp(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId minVal, SpvId maxVal) {
	SpvId args[3]{ x, minVal, maxVal };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 43, args, 3);
}
SpvId op_u_clamp(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId minVal, SpvId maxVal) {
	SpvId args[3]{ x, minVal, maxVal };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 44, args, 3);
}
SpvId op_s_clamp(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId minVal, SpvId maxVal) {
	SpvId args[3]{ x, minVal, maxVal };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 45, args, 3);
}
SpvId op_f_mix(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId y, SpvId a) {
	SpvId args[3]{ x, y, a };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 46, args, 3);
}
SpvId op_f_step(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId edge, SpvId x) {
	SpvId args[2]{ edge, x };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 48, args, 2);
}
SpvId op_f_smoothstep(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId edge0, SpvId edge1, SpvId x) {
	SpvId args[3]{ edge0, edge1, x };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 49, args, 3);
}
SpvId op_f_fma(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId a, SpvId b, SpvId c) {
	SpvId args[3]{ a, b, c };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 50, args, 3);
}
SpvId op_f_sin(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 13, &x, 1);
}
SpvId op_f_cos(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 14, &x, 1);
}
SpvId op_f_tan(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 15, &x, 1);
}
SpvId op_f_asin(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 16, &x, 1);
}
SpvId op_f_acos(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 17, &x, 1);
}
SpvId op_f_atan(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 18, &x, 1);
}
SpvId op_f_atan2(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId y, SpvId x) {
	SpvId args[2]{ y, x };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 25, args, 2);
}
SpvId op_f_pow(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId y) {
	SpvId args[2]{ x, y };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 26, args, 2);
}
SpvId op_f_exp(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 27, &x, 1);
}
SpvId op_f_log(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 28, &x, 1);
}
SpvId op_f_exp2(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 29, &x, 1);
}
SpvId op_f_log2(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 30, &x, 1);
}
SpvId op_f_sqrt(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 31, &x, 1);
}
SpvId op_f_invsqrt(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 32, &x, 1);
}
SpvId op_f_reflect(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId i, SpvId n) {
	SpvId args[2]{ i, n };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 71, args, 2);
}
SpvId op_f_round(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 1, &x, 1);
}
SpvId op_f_trunc(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 3, &x, 1);
}
SpvId op_f_abs(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 4, &x, 1);
}
SpvId op_f_floor(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 8, &x, 1);
}
SpvId op_f_ceil(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 9, &x, 1);
}
SpvId op_f_fract(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 10, &x, 1);
}
SpvId op_frexp(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x) {
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 52, &x, 1);
}
SpvId op_ldexp(ArenaArrayList<SpvDword>& output, SpvId resultType, SpvId resultId, SpvId glsl450InstructionSet, SpvId x, SpvId exp) {
	SpvId args[2]{ x, exp };
	return op_ext_inst(output, resultType, resultId, glsl450InstructionSet, 53, args, 2);
}



}